version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: mi-ecommerce-api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:17
    container_name: postgresdb
    env_file:
      - ./api/.env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: