services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mi-ecommerce-api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: postgres:17
    container_name: postgresdb
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  pgdata: